/* Bootstrap references; regenerated by `pnpm exec convex codegen`. */
import { anyApi } from "convex/server";
import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import type * as rooms from "../rooms";
import type * as cleanup from "../cleanup";
const fullApi = anyApi as unknown as ApiFromModules<{ rooms: typeof rooms; cleanup: typeof cleanup }>;
export const api = fullApi as FilterApi<typeof fullApi, FunctionReference<"query" | "mutation", "public">>;
export const internal = fullApi as FilterApi<typeof fullApi, FunctionReference<"mutation", "internal">>;
