/* Bootstrap types; regenerated by `pnpm exec convex codegen`. */
import { queryGeneric, mutationGeneric, internalMutationGeneric } from "convex/server";
import type { QueryBuilder, MutationBuilder, GenericQueryCtx, GenericMutationCtx } from "convex/server";
import type { DataModel } from "./dataModel";
export const query: QueryBuilder<DataModel, "public"> = queryGeneric;
export const mutation: MutationBuilder<DataModel, "public"> = mutationGeneric;
export const internalMutation: MutationBuilder<DataModel, "internal"> = internalMutationGeneric;
export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
